### ISSUE TITLE
About EXAMPLE

### ISSUE THREAD

**Issue by MrLevo520** [ikki407/stacking#46]
Hi
    I find something maybe you don't notice 
    1. First of all, run 'pip install stacking' , it's not work for macOS because the xgboost package can't  install here automatic，so we need install xgboost first manually.
    2. I notice that in  "examples/multi_class/scripts/multiclass.py"  , something wrong in  line 25 ,it should be "from keras.regularizers import l1, l2" ,little mistake but make 'bash run.sh' can't work
    3. 'No module named paratext'  is another problem ,the solution is git from https://github.com/wiseio/paratext, and don't forget to install swig by using 'brew install swig' if brew have been installed

That's it ,now i can run the EXAMPLE, i suggest the environment should write in README.md just in case. 
BTW, project is wonderful！

**Comment by ikki407** [comment]
Thank you for your suggestions and so sorry for the too late reply.
Some libraries (XGB, Keras, ...) used in this repository are too outdated.
I need to fix them.
I will fix them and your suggestions at the end of the year.

Thanks!!

**Comment by ikki407** [comment]
Done! Thanks!
